# Development Docker Compose - Optimized for local development with hot reload
services:
  mongodb:
    image: mongo:7.0
    container_name: infra-mind-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: infra_mind
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - infra-mind-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  redis:
    image: redis:7.2-alpine
    container_name: infra-mind-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - infra-mind-network
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  mongo-express:
    image: mongo-express:1.0.0
    container_name: infra-mind-mongo-express-dev
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - infra-mind-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: infra-mind-api-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8001:8001"  # Debug port
    environment:
      INFRA_MIND_MONGODB_URL: mongodb://admin:password@mongodb:27017/infra_mind?authSource=admin
      INFRA_MIND_REDIS_URL: redis://redis:6379
      INFRA_MIND_ENVIRONMENT: development
      INFRA_MIND_DEBUG: "true"
      INFRA_MIND_LOG_LEVEL: DEBUG
      INFRA_MIND_SECRET_KEY: dev-secret-key-change-in-production
      JWT_SECRET_KEY: dev-jwt-secret-key-change-in-production
      INFRA_MIND_CORS_ORIGINS: '["http://localhost:3000", "http://frontend:3000", "http://127.0.0.1:3000"]'
      # Development features
      INFRA_MIND_ENABLE_PROFILING: "true"
      INFRA_MIND_ENABLE_TRACING: "true"
      INFRA_MIND_RELOAD_DIRS: "/app/src"
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
      - ./tests:/app/tests:ro
    networks:
      - infra-mind-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 45s

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
      target: development
    container_name: infra-mind-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:8000
      NEXT_PUBLIC_WS_URL: ws://localhost:8000
      NEXT_TELEMETRY_DISABLED: 1
      FAST_REFRESH: "true"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./frontend-react/src:/app/src:ro
      - ./frontend-react/public:/app/public:ro
      - ./frontend-react/package.json:/app/package.json:ro
      - ./frontend-react/next.config.ts:/app/next.config.ts:ro
      - ./frontend-react/tailwind.config.js:/app/tailwind.config.js:ro
      - ./frontend-react/tsconfig.json:/app/tsconfig.json:ro
      - /app/node_modules
      - /app/.next
    networks:
      - infra-mind-network
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Development tools (activated with --profile tools)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: infra-mind-redis-commander-dev
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis
    networks:
      - infra-mind-network
    profiles:
      - tools

volumes:
  mongodb_data:
  redis_data:

networks:
  infra-mind-network:
    driver: bridge