apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-mind-frontend
  namespace: infra-mind
  labels:
    app: infra-mind-frontend
    component: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: infra-mind-frontend
  template:
    metadata:
      labels:
        app: infra-mind-frontend
        component: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: frontend
        image: infra-mind/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: infra-mind-config
              key: NEXT_PUBLIC_API_URL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: infra-mind-config
              key: NODE_ENV
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 20

---
apiVersion: v1
kind: Service
metadata:
  name: infra-mind-frontend-service
  namespace: infra-mind
  labels:
    app: infra-mind-frontend
spec:
  selector:
    app: infra-mind-frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: infra-mind-frontend-pdb
  namespace: infra-mind
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: infra-mind-frontend